version: "3.7"
services:
  wordpress:
    restart: always
    build: 
      context: ./requirements/wordpress
    networks:
      - docker-network
    volumes:
      - wp:/var/www
      
  mariadb:
    restart: always
    build: 
      context: ./requirements/mariadb
    networks:
      - docker-network
    volumes:
      - wp:/var/lib/mysql
    environment:
      - DB_NAME=wordpress
      - DB_ROOT_PASSWORD=root
      - DB_USER=hheimerd
      - DB_PASSWORD=1234

  nginx:
    # restart: always
    build: 
      args: 
        - CERT_PATH=./ssl
      context: ./requirements/nginx
    networks:
      - docker-network
    volumes:
      - wp:/var/www
    environment:
      - NGINX_SSL_PORT=443
      - NGINX_HOST=hheimerd.42.fr
    ports:
      - 443:443
      - 80:80

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress
      type: none
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      device: $VOLUME_PATH
      type: none
      o: bind
      


networks: 
  docker-network:
    driver: bridge

