version: "3.5"
services:
  wordpress:
    container_name: wordpress
    restart: unless-stopped
    build: 
      context: ./requirements/wordpress
    depends_on: 
      - database
      - redis
      - nginx
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=database
    networks:
      - docker-network
    volumes:
      - wp:/var/www

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: 
      args: 
        - CERT_PATH=$CERT_PATH
      context: ./requirements/nginx
    networks:
      - docker-network
    volumes:
      - wp:/var/www
    environment:
      - NGINX_HOST=$HOSTNAME
    ports:
      - 443:443

  node:
    container_name: node
    restart: unless-stopped
    build:
      context: ./requirements/node
    environment:
      - NODE_ENV=production
    networks:
      - docker-network
    volumes:
      - node-app:/app
    command: "sh -c 'npx create-react-app app; cd app && npm i && npm start'"
    ports:
      - 3000:3000

  ftp:
    container_name: ftp
    restart: unless-stopped
    build:
      args:
        - FTP_USER=$FTP_USER
        - FTP_PASS=$FTP_PASS
      context: ./requirements/ftp
    networks:
      - docker-network
    volumes:
      - wp:/ftp
    ports:
      - "20:20"
      - "${FTP_PORT}:21"
      - "21000:21000"

  database:
    container_name: database
    restart: unless-stopped
    build: 
      context: ./requirements/database
    networks:
      - docker-network
    volumes:
      - db:/var/lib/mysql
    environment:
      - DB_NAME=$DB_NAME
      - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD

  adminer:
    container_name: adminer
    restart: unless-stopped
    build: 
      context: ./requirements/adminer
    networks:
      - docker-network

  redis:
    container_name: redis
    restart: unless-stopped
    build: 
      context: ./requirements/redis
    networks:
      - docker-network

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress_data
      type: none
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/database
      type: none
      o: bind
  node-app:
    name: node-app
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/node-app
      type: none
      o: bind


networks: 
  docker-network:
    driver: bridge

