version: "3.7"
services:
  wordpress:
    restart: always
    build: 
      context: ./requirements/wordpress
    networks:
      - docker-network
    volumes:
      - wp:/var/www

  nginx:
    # restart: always
    build: 
      args: 
        - CERT_PATH=$CERT_PATH
      context: ./requirements/nginx
    networks:
      - docker-network
    volumes:
      - wp:/var/www
    environment:
      - NGINX_HOST=$HOSTNAME
    ports:
      - 443:443

      
  mariadb:
    restart: always
    build: 
      context: ./requirements/mariadb
    networks:
      - docker-network
    volumes:
      - db:/var/lib/mysql
    environment:
      - DB_NAME=$DB_NAME
      - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD

  adminer:
    restart: always
    build: 
      context: ./requirements/adminer
    networks:
      - docker-network

  redis:
    restart: always
    build: 
      context: ./requirements/redis
    networks:
      - docker-network
    ports:
      - 6379:6379

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress_data
      type: none
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      device: $VOLUME_PATH
      type: none
      o: bind
      


networks: 
  docker-network:
    driver: bridge

