FROM debian:buster

RUN apt update && \
    apt install -y mariadb-server gettext-base sudo

COPY ./entry.sh /entry.sh
COPY ./init.sql /tmp/init.sql
COPY ./templates/my.cnf etc/mysql/conf.d/my.cnf

RUN chmod +x ./entry.sh

ENTRYPOINT [ "/entry.sh" ]
CMD [ "mysqld"]