FROM debian:buster

RUN apt update && \
    apt install -y mariadb-server gettext-base

COPY ./entry.sh /entry.sh
COPY ./init.sql /tmp/init.sql
COPY ./my.cnf /etc/mysql/my.cnf

RUN chmod +x ./entry.sh

ENTRYPOINT [ "/entry.sh" ]
CMD [ "mysqld"]