FROM debian:buster

ARG DB_ADMIN_PASSWORD
ARG DB_USER
ARG DB_PASSWORD

RUN apt update && \
    apt install -y mariadb-server supervisor && \
    service mysql start;

RUN mysql_install_db --datadir"/home/hheimerd/data"

RUN mysqladmin --user=root password $DB_ROOT_PASSWORD;

RUN echo "CREATE USER $DB_USER IDENTIFIED by  '$DB_PASSWORD';" | mysql;