FROM debian:buster

RUN apt-get update && \
    apt-get install -y php-fpm php-mbstring php-cli php-mysql gettext-base php-redis unzip mariadb-client


RUN mkdir /run/php

COPY ./www.conf /etc/php/7.3/fpm/pool.d/www.conf

ADD ./wordpress.zip /tmp/wordpress.zip
RUN unzip /tmp/wordpress.zip -d /tmp/


# ADD https://wordpress.org/latest.zip /tmp/wordpress

ADD https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar /usr/local/bin/wp
RUN chmod +x /usr/local/bin/wp

COPY ./entry.sh /tmp/entry.sh
COPY ./wp-config.php /tmp/wp-config.php

ENTRYPOINT ["sh", "/tmp/entry.sh"]

CMD ["/usr/sbin/php-fpm7.3", "-F", "-R"]