FROM debian:buster

RUN apt update && \
    apt install -y php-fpm php-mbstring php-mysql
 
RUN mkdir /run/php

COPY ./www.conf /etc/php/7.3/fpm/pool.d/www.conf
COPY ./start.sh /tmp/start.sh

CMD ["sh", "/tmp/start.sh"]