FROM debian:buster

RUN apt update && \
    apt install -y nginx gettext-base supervisor openssl;

RUN useradd www


COPY ./entry.sh /
RUN ["chmod", "+x", "/entry.sh"]
ENTRYPOINT ["/entry.sh"]


RUN mkdir -p /etc/.ssl
ARG CERT_PATH
COPY $CERT_PATH /etc/.ssl/

COPY templates/nginx.conf /

