FROM debian:buster

RUN apt update && \
    apt install -y nginx gettext-base openssl;

RUN useradd www

RUN mkdir -p /etc/.ssl
ARG CERT_PATH
COPY $CERT_PATH /etc/.ssl/

COPY templates/nginx.conf /

COPY ./entry.sh /entry.sh
RUN ["chmod", "+x", "/entry.sh"]

CMD ["sh", "/entry.sh"]